---
- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Get DEB architecture
  command: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Add Docker's official repository
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: yes

- name: Install Docker Engine
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
